"use client"

import { createContext, useContext, useState, useEffect, type ReactNode } from "react"

type Language = "pt" | "en" | "es" | "fr" | "de" | "zh" | "ar" | "hi"

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

const translations = {
  pt: {
    // Header
    "header.search": "Buscar produtos...",
    "header.cart": "Carrinho",
    "header.login": "Entrar",
    "header.register": "Cadastrar",
    "header.dashboard": "Dashboard",
    "header.logout": "Sair",
    "header.myAccount": "Minha Conta",
    "header.panel": "Painel",

    // Footer
    "footer.about": "Sobre Nós",
    "footer.contact": "Contato",
    "footer.terms": "Termos de Uso",
    "footer.privacy": "Política de Privacidade",
    "footer.rights": "Todos os direitos reservados",

    // Home
    "home.title": "Achadinhos Xpress",
    "home.subtitle": "As melhores ofertas em um só lugar",
    "home.filters": "Filtros",
    "home.sortBy": "Ordenar por",
    "home.sortRecent": "Mais recentes",
    "home.sortPriceLow": "Menor preço",
    "home.sortPriceHigh": "Maior preço",
    "home.sortViews": "Mais vistos",
    "home.stores": "Lojas",
    "home.categories": "Categorias",
    "home.clearFilters": "Limpar filtros",
    "home.noProducts": "Nenhum produto encontrado",
    "home.viewOffer": "Ver oferta",
    "home.addToCart": "Adicionar",

    // Product Modal
    "product.description": "Descrição",
    "product.characteristics": "Características",
    "product.addToCart": "Adicionar ao carrinho",
    "product.buyNow": "Comprar agora",
    "product.close": "Fechar",

    // Cart
    "cart.title": "Carrinho de Compras",
    "cart.empty": "Seu carrinho está vazio",
    "cart.continueShopping": "Continuar comprando",
    "cart.store": "Loja",
    "cart.quantity": "Quantidade",
    "cart.price": "Preço",
    "cart.total": "Total",
    "cart.remove": "Remover",
    "cart.buy": "Comprar",
    "cart.clearAll": "Limpar carrinho",

    // Auth
    "auth.login": "Entrar",
    "auth.register": "Cadastrar",
    "auth.email": "E-mail",
    "auth.password": "Senha",
    "auth.confirmPassword": "Confirmar senha",
    "auth.name": "Nome completo",
    "auth.forgotPassword": "Esqueceu a senha?",
    "auth.noAccount": "Não tem uma conta?",
    "auth.hasAccount": "Já tem uma conta?",
    "auth.resetPassword": "Redefinir senha",
    "auth.sendResetLink": "Enviar link de redefinição",
    "auth.backToLogin": "Voltar ao login",
    "auth.loggingIn": "Entrando...",
    "auth.registering": "Cadastrando...",
    "auth.sending": "Enviando...",

    // Dashboard
    "dashboard.title": "Dashboard Administrativo",
    "dashboard.products": "Produtos",
    "dashboard.reports": "Relatórios",
    "dashboard.admins": "Administradores",
    "dashboard.config": "Configurações",
    "dashboard.addProduct": "Adicionar Produto",
    "dashboard.editProduct": "Editar Produto",
    "dashboard.deleteProduct": "Excluir Produto",
    "dashboard.confirmDelete": "Tem certeza que deseja excluir este produto?",
    "dashboard.cancel": "Cancelar",
    "dashboard.delete": "Excluir",
    "dashboard.save": "Salvar",
    "dashboard.saving": "Salvando...",

    // Product Form
    "form.title": "Título",
    "form.description": "Descrição",
    "form.price": "Preço",
    "form.originalPrice": "Preço original",
    "form.store": "Loja",
    "form.category": "Categoria",
    "form.link": "Link do produto",
    "form.images": "Imagens",
    "form.video": "Vídeo",
    "form.stock": "Quantidade em Estoque (opcional)",
    "form.published": "Visível no Site",
    "form.publishedHelp": "Quando ativado, o produto aparece na vitrine",
    "form.active": "Disponível para Venda",
    "form.activeHelp": "Quando ativado, o produto pode ser adicionado ao carrinho",
    "form.productCode": "Código do Produto",
    "form.barcode": "Código de Barras",
    "form.globalCode": "Código Global",

    // Reports
    "reports.overview": "Visão Geral",
    "reports.totalProducts": "Total de Produtos",
    "reports.activeProducts": "Produtos Ativos",
    "reports.totalViews": "Total de Visualizações",
    "reports.cartAdditions": "Adições ao Carrinho",
    "reports.salesByStore": "Vendas por Loja",
    "reports.salesByCategory": "Vendas por Categoria",
    "reports.topProducts": "Produtos Mais Vistos",
    "reports.views": "visualizações",

    // Admins
    "admins.title": "Gerenciar Administradores",
    "admins.addAdmin": "Adicionar Administrador",
    "admins.email": "E-mail",
    "admins.role": "Função",
    "admins.createdAt": "Criado em",
    "admins.actions": "Ações",
    "admins.remove": "Remover",
    "admins.confirmRemove": "Tem certeza que deseja remover este administrador?",

    // Config
    "config.title": "Configurações do Sistema",
    "config.backup": "Backup e Restauração",
    "config.exportData": "Exportar Dados",
    "config.importData": "Importar Dados",
    "config.exporting": "Exportando...",
    "config.importing": "Importando...",
    "config.selectFile": "Selecionar arquivo",

    // Categories
    "category.fashion": "Moda",
    "category.footwear": "Calçados",
    "category.jewelry": "Joias e Acessórios",
    "category.electronics": "Eletrônicos",
    "category.appliances": "Eletrodomésticos",
    "category.furniture": "Móveis",
    "category.sports": "Esportes",
    "category.toys": "Brinquedos",
    "category.books": "Livros",
    "category.beauty": "Beleza",
    "category.health": "Saúde",
    "category.automotive": "Automotivo",
    "category.tools": "Ferramentas",
    "category.garden": "Jardim",
    "category.pets": "Pet Shop",
    "category.baby": "Bebê",
    "category.office": "Escritório",
    "category.instruments": "Instrumentos Musicais",
    "category.games": "Games",
    "category.food": "Alimentos",
    "category.drinks": "Bebidas",
    "category.cleaning": "Limpeza",
    "category.collectibles": "Colecionáveis",
    "category.party": "Festas",
    "category.industrial": "Industrial",
    "category.ppe": "EPIs",
    "category.services": "Serviços",

    // Common
    "common.loading": "Carregando...",
    "common.error": "Erro",
    "common.success": "Sucesso",
    "common.confirm": "Confirmar",
    "common.cancel": "Cancelar",
    "common.save": "Salvar",
    "common.edit": "Editar",
    "common.delete": "Excluir",
    "common.search": "Buscar",
    "common.filter": "Filtrar",
    "common.sort": "Ordenar",
    "common.previous": "Anterior",
    "common.next": "Próximo",
    "common.page": "Página",
    "common.of": "de",
  },
  en: {
    // Header
    "header.search": "Search products...",
    "header.cart": "Cart",
    "header.login": "Login",
    "header.register": "Register",
    "header.dashboard": "Dashboard",
    "header.logout": "Logout",
    "header.myAccount": "My Account",
    "header.panel": "Panel",

    // Footer
    "footer.about": "About Us",
    "footer.contact": "Contact",
    "footer.terms": "Terms of Use",
    "footer.privacy": "Privacy Policy",
    "footer.rights": "All rights reserved",

    // Home
    "home.title": "Achadinhos Xpress",
    "home.subtitle": "The best deals in one place",
    "home.filters": "Filters",
    "home.sortBy": "Sort by",
    "home.sortRecent": "Most recent",
    "home.sortPriceLow": "Lowest price",
    "home.sortPriceHigh": "Highest price",
    "home.sortViews": "Most viewed",
    "home.stores": "Stores",
    "home.categories": "Categories",
    "home.clearFilters": "Clear filters",
    "home.noProducts": "No products found",
    "home.viewOffer": "View offer",
    "home.addToCart": "Add",

    // Product Modal
    "product.description": "Description",
    "product.characteristics": "Characteristics",
    "product.addToCart": "Add to cart",
    "product.buyNow": "Buy now",
    "product.close": "Close",

    // Cart
    "cart.title": "Shopping Cart",
    "cart.empty": "Your cart is empty",
    "cart.continueShopping": "Continue shopping",
    "cart.store": "Store",
    "cart.quantity": "Quantity",
    "cart.price": "Price",
    "cart.total": "Total",
    "cart.remove": "Remove",
    "cart.buy": "Buy",
    "cart.clearAll": "Clear cart",

    // Auth
    "auth.login": "Login",
    "auth.register": "Register",
    "auth.email": "Email",
    "auth.password": "Password",
    "auth.confirmPassword": "Confirm password",
    "auth.name": "Full name",
    "auth.forgotPassword": "Forgot password?",
    "auth.noAccount": "Don't have an account?",
    "auth.hasAccount": "Already have an account?",
    "auth.resetPassword": "Reset password",
    "auth.sendResetLink": "Send reset link",
    "auth.backToLogin": "Back to login",
    "auth.loggingIn": "Logging in...",
    "auth.registering": "Registering...",
    "auth.sending": "Sending...",

    // Dashboard
    "dashboard.title": "Admin Dashboard",
    "dashboard.products": "Products",
    "dashboard.reports": "Reports",
    "dashboard.admins": "Administrators",
    "dashboard.config": "Settings",
    "dashboard.addProduct": "Add Product",
    "dashboard.editProduct": "Edit Product",
    "dashboard.deleteProduct": "Delete Product",
    "dashboard.confirmDelete": "Are you sure you want to delete this product?",
    "dashboard.cancel": "Cancel",
    "dashboard.delete": "Delete",
    "dashboard.save": "Save",
    "dashboard.saving": "Saving...",

    // Product Form
    "form.title": "Title",
    "form.description": "Description",
    "form.price": "Price",
    "form.originalPrice": "Original price",
    "form.store": "Store",
    "form.category": "Category",
    "form.link": "Product link",
    "form.images": "Images",
    "form.video": "Video",
    "form.stock": "Stock Quantity (optional)",
    "form.published": "Visible on Site",
    "form.publishedHelp": "When enabled, product appears in storefront",
    "form.active": "Available for Sale",
    "form.activeHelp": "When enabled, product can be added to cart",
    "form.productCode": "Product Code",
    "form.barcode": "Barcode",
    "form.globalCode": "Global Code",

    // Reports
    "reports.overview": "Overview",
    "reports.totalProducts": "Total Products",
    "reports.activeProducts": "Active Products",
    "reports.totalViews": "Total Views",
    "reports.cartAdditions": "Cart Additions",
    "reports.salesByStore": "Sales by Store",
    "reports.salesByCategory": "Sales by Category",
    "reports.topProducts": "Most Viewed Products",
    "reports.views": "views",

    // Admins
    "admins.title": "Manage Administrators",
    "admins.addAdmin": "Add Administrator",
    "admins.email": "Email",
    "admins.role": "Role",
    "admins.createdAt": "Created at",
    "admins.actions": "Actions",
    "admins.remove": "Remove",
    "admins.confirmRemove": "Are you sure you want to remove this administrator?",

    // Config
    "config.title": "System Settings",
    "config.backup": "Backup and Restore",
    "config.exportData": "Export Data",
    "config.importData": "Import Data",
    "config.exporting": "Exporting...",
    "config.importing": "Importing...",
    "config.selectFile": "Select file",

    // Categories
    "category.fashion": "Fashion",
    "category.footwear": "Footwear",
    "category.jewelry": "Jewelry & Accessories",
    "category.electronics": "Electronics",
    "category.appliances": "Appliances",
    "category.furniture": "Furniture",
    "category.sports": "Sports",
    "category.toys": "Toys",
    "category.books": "Books",
    "category.beauty": "Beauty",
    "category.health": "Health",
    "category.automotive": "Automotive",
    "category.tools": "Tools",
    "category.garden": "Garden",
    "category.pets": "Pet Shop",
    "category.baby": "Baby",
    "category.office": "Office",
    "category.instruments": "Musical Instruments",
    "category.games": "Games",
    "category.food": "Food",
    "category.drinks": "Drinks",
    "category.cleaning": "Cleaning",
    "category.collectibles": "Collectibles",
    "category.party": "Party Supplies",
    "category.industrial": "Industrial",
    "category.ppe": "PPE",
    "category.services": "Services",

    // Common
    "common.loading": "Loading...",
    "common.error": "Error",
    "common.success": "Success",
    "common.confirm": "Confirm",
    "common.cancel": "Cancel",
    "common.save": "Save",
    "common.edit": "Edit",
    "common.delete": "Delete",
    "common.search": "Search",
    "common.filter": "Filter",
    "common.sort": "Sort",
    "common.previous": "Previous",
    "common.next": "Next",
    "common.page": "Page",
    "common.of": "of",
  },
  es: {
    "header.search": "Buscar productos...",
    "header.cart": "Carrito",
    "header.login": "Iniciar sesión",
    "header.register": "Registrarse",
    "header.logout": "Cerrar sesión",
    "header.myAccount": "Mi Cuenta",
    "header.panel": "Panel",
    "home.title": "Achadinhos Xpress",
    "home.subtitle": "Las mejores ofertas en un solo lugar",
    "home.filters": "Filtros",
    "home.sortBy": "Ordenar por",
    "home.sortRecent": "Más recientes",
    "home.sortPriceLow": "Precio más bajo",
    "home.sortPriceHigh": "Precio más alto",
    "home.sortViews": "Más vistos",
    "home.stores": "Tiendas",
    "home.categories": "Categorías",
    "home.clearFilters": "Limpiar filtros",
    "home.noProducts": "No se encontraron productos",
    "home.viewOffer": "Ver oferta",
    "home.addToCart": "Agregar",
    "product.description": "Descripción",
    "product.characteristics": "Características",
    "product.addToCart": "Agregar al carrito",
    "product.buyNow": "Comprar ahora",
    "product.close": "Cerrar",
    "cart.title": "Carrito de Compras",
    "cart.empty": "Tu carrito está vacío",
    "cart.continueShopping": "Continuar comprando",
    "cart.store": "Tienda",
    "cart.quantity": "Cantidad",
    "cart.price": "Precio",
    "cart.total": "Total",
    "cart.remove": "Eliminar",
    "cart.buy": "Comprar",
    "cart.clearAll": "Vaciar carrito",
    "form.productCode": "Código del Producto",
    "form.barcode": "Código de Barras",
    "form.globalCode": "Código Global",
    "form.stock": "Cantidad en Stock (opcional)",
    "form.published": "Visible en el Sitio",
    "form.publishedHelp": "Cuando está activado, el producto aparece en la tienda",
    "form.active": "Disponible para Venta",
    "form.activeHelp": "Cuando está activado, el producto se puede agregar al carrito",
    "category.fashion": "Moda",
    "category.footwear": "Calzado",
    "category.jewelry": "Joyas y Accesorios",
    "category.electronics": "Electrónicos",
    "category.appliances": "Electrodomésticos",
    "category.furniture": "Muebles",
    "category.sports": "Deportes",
    "category.toys": "Juguetes",
    "category.books": "Libros",
    "category.beauty": "Belleza",
    "category.health": "Salud",
    "category.automotive": "Automotriz",
    "category.tools": "Herramientas",
    "category.garden": "Jardín",
    "category.pets": "Mascotas",
    "category.baby": "Bebé",
    "category.office": "Oficina",
    "category.instruments": "Instrumentos Musicales",
    "category.games": "Juegos",
    "category.food": "Alimentos",
    "category.drinks": "Bebidas",
    "category.cleaning": "Limpieza",
    "category.collectibles": "Coleccionables",
    "category.party": "Fiestas",
    "category.industrial": "Industrial",
    "category.ppe": "EPP",
    "category.services": "Servicios",
    "common.loading": "Cargando...",
    "common.error": "Error",
    "common.success": "Éxito",
    "common.confirm": "Confirmar",
    "common.cancel": "Cancelar",
    "common.save": "Guardar",
    "common.edit": "Editar",
    "common.delete": "Eliminar",
  },
  fr: {
    "header.search": "Rechercher des produits...",
    "header.cart": "Panier",
    "header.login": "Connexion",
    "header.register": "S'inscrire",
    "header.logout": "Déconnexion",
    "header.myAccount": "Mon Compte",
    "header.panel": "Panneau",
    "home.title": "Achadinhos Xpress",
    "home.subtitle": "Les meilleures offres en un seul endroit",
    "home.filters": "Filtres",
    "home.sortBy": "Trier par",
    "home.sortRecent": "Plus récents",
    "home.sortPriceLow": "Prix le plus bas",
    "home.sortPriceHigh": "Prix le plus élevé",
    "home.sortViews": "Les plus vus",
    "home.stores": "Magasins",
    "home.categories": "Catégories",
    "home.clearFilters": "Effacer les filtres",
    "home.noProducts": "Aucun produit trouvé",
    "home.viewOffer": "Voir l'offre",
    "home.addToCart": "Ajouter",
    "product.description": "Description",
    "product.characteristics": "Caractéristiques",
    "product.addToCart": "Ajouter au panier",
    "product.buyNow": "Acheter maintenant",
    "product.close": "Fermer",
    "cart.title": "Panier d'Achat",
    "cart.empty": "Votre panier est vide",
    "cart.continueShopping": "Continuer les achats",
    "cart.store": "Magasin",
    "cart.quantity": "Quantité",
    "cart.price": "Prix",
    "cart.total": "Total",
    "cart.remove": "Supprimer",
    "cart.buy": "Acheter",
    "cart.clearAll": "Vider le panier",
    "form.productCode": "Code Produit",
    "form.barcode": "Code-barres",
    "form.globalCode": "Code Global",
    "form.stock": "Quantité en Stock (optionnel)",
    "form.published": "Visible sur le Site",
    "form.publishedHelp": "Lorsqu'activé, le produit apparaît en vitrine",
    "form.active": "Disponible à la Vente",
    "form.activeHelp": "Lorsqu'activé, le produit peut être ajouté au panier",
    "category.fashion": "Mode",
    "category.footwear": "Chaussures",
    "category.jewelry": "Bijoux et Accessoires",
    "category.electronics": "Électronique",
    "category.appliances": "Électroménager",
    "category.furniture": "Meubles",
    "category.sports": "Sports",
    "category.toys": "Jouets",
    "category.books": "Livres",
    "category.beauty": "Beauté",
    "category.health": "Santé",
    "category.automotive": "Automobile",
    "category.tools": "Outils",
    "category.garden": "Jardin",
    "category.pets": "Animalerie",
    "category.baby": "Bébé",
    "category.office": "Bureau",
    "category.instruments": "Instruments de Musique",
    "category.games": "Jeux",
    "category.food": "Alimentation",
    "category.drinks": "Boissons",
    "category.cleaning": "Nettoyage",
    "category.collectibles": "Objets de Collection",
    "category.party": "Fêtes",
    "category.industrial": "Industriel",
    "category.ppe": "EPI",
    "category.services": "Services",
    "common.loading": "Chargement...",
    "common.error": "Erreur",
    "common.success": "Succès",
    "common.confirm": "Confirmer",
    "common.cancel": "Annuler",
    "common.save": "Enregistrer",
    "common.edit": "Modifier",
    "common.delete": "Supprimer",
  },
  de: {
    "header.search": "Produkte suchen...",
    "header.cart": "Warenkorb",
    "header.login": "Anmelden",
    "header.register": "Registrieren",
    "header.logout": "Abmelden",
    "header.myAccount": "Mein Konto",
    "header.panel": "Panel",
    "home.title": "Achadinhos Xpress",
    "home.subtitle": "Die besten Angebote an einem Ort",
    "home.filters": "Filter",
    "home.sortBy": "Sortieren nach",
    "home.sortRecent": "Neueste",
    "home.sortPriceLow": "Niedrigster Preis",
    "home.sortPriceHigh": "Höchster Preis",
    "home.sortViews": "Meistgesehen",
    "home.stores": "Geschäfte",
    "home.categories": "Kategorien",
    "home.clearFilters": "Filter löschen",
    "home.noProducts": "Keine Produkte gefunden",
    "home.viewOffer": "Angebot ansehen",
    "home.addToCart": "Hinzufügen",
    "product.description": "Beschreibung",
    "product.characteristics": "Eigenschaften",
    "product.addToCart": "In den Warenkorb",
    "product.buyNow": "Jetzt kaufen",
    "product.close": "Schließen",
    "cart.title": "Warenkorb",
    "cart.empty": "Ihr Warenkorb ist leer",
    "cart.continueShopping": "Weiter einkaufen",
    "cart.store": "Geschäft",
    "cart.quantity": "Menge",
    "cart.price": "Preis",
    "cart.total": "Gesamt",
    "cart.remove": "Entfernen",
    "cart.buy": "Kaufen",
    "cart.clearAll": "Warenkorb leeren",
    "form.productCode": "Produktcode",
    "form.barcode": "Barcode",
    "form.globalCode": "Globaler Code",
    "form.stock": "Lagerbestand (optional)",
    "form.published": "Auf der Website sichtbar",
    "form.publishedHelp": "Wenn aktiviert, erscheint das Produkt im Shop",
    "form.active": "Zum Verkauf verfügbar",
    "form.activeHelp": "Wenn aktiviert, kann das Produkt in den Warenkorb gelegt werden",
    "category.fashion": "Mode",
    "category.footwear": "Schuhe",
    "category.jewelry": "Schmuck und Accessoires",
    "category.electronics": "Elektronik",
    "category.appliances": "Haushaltsgeräte",
    "category.furniture": "Möbel",
    "category.sports": "Sport",
    "category.toys": "Spielzeug",
    "category.books": "Bücher",
    "category.beauty": "Schönheit",
    "category.health": "Gesundheit",
    "category.automotive": "Automobil",
    "category.tools": "Werkzeuge",
    "category.garden": "Garten",
    "category.pets": "Haustiere",
    "category.baby": "Baby",
    "category.office": "Büro",
    "category.instruments": "Musikinstrumente",
    "category.games": "Spiele",
    "category.food": "Lebensmittel",
    "category.drinks": "Getränke",
    "category.cleaning": "Reinigung",
    "category.collectibles": "Sammlerstücke",
    "category.party": "Party",
    "category.industrial": "Industrie",
    "category.ppe": "PSA",
    "category.services": "Dienstleistungen",
    "common.loading": "Laden...",
    "common.error": "Fehler",
    "common.success": "Erfolg",
    "common.confirm": "Bestätigen",
    "common.cancel": "Abbrechen",
    "common.save": "Speichern",
    "common.edit": "Bearbeiten",
    "common.delete": "Löschen",
  },
  zh: {
    "header.search": "搜索产品...",
    "header.cart": "购物车",
    "header.login": "登录",
    "header.register": "注册",
    "header.logout": "退出",
    "header.myAccount": "我的账户",
    "header.panel": "面板",
    "home.title": "Achadinhos Xpress",
    "home.subtitle": "一站式最佳优惠",
    "home.filters": "筛选",
    "home.sortBy": "排序",
    "home.sortRecent": "最新",
    "home.sortPriceLow": "价格最低",
    "home.sortPriceHigh": "价格最高",
    "home.sortViews": "最多浏览",
    "home.stores": "商店",
    "home.categories": "类别",
    "home.clearFilters": "清除筛选",
    "home.noProducts": "未找到产品",
    "home.viewOffer": "查看优惠",
    "home.addToCart": "添加",
    "product.description": "描述",
    "product.characteristics": "特征",
    "product.addToCart": "加入购物车",
    "product.buyNow": "立即购买",
    "product.close": "关闭",
    "cart.title": "购物车",
    "cart.empty": "您的购物车是空的",
    "cart.continueShopping": "继续购物",
    "cart.store": "商店",
    "cart.quantity": "数量",
    "cart.price": "价格",
    "cart.total": "总计",
    "cart.remove": "移除",
    "cart.buy": "购买",
    "cart.clearAll": "清空购物车",
    "form.productCode": "产品代码",
    "form.barcode": "条形码",
    "form.globalCode": "全球代码",
    "form.stock": "库存数量（可选）",
    "form.published": "在网站上可见",
    "form.publishedHelp": "启用后，产品将显示在店面",
    "form.active": "可供销售",
    "form.activeHelp": "启用后，产品可以添加到购物车",
    "category.fashion": "时尚",
    "category.footwear": "鞋类",
    "category.jewelry": "珠宝和配饰",
    "category.electronics": "电子产品",
    "category.appliances": "家用电器",
    "category.furniture": "家具",
    "category.sports": "运动",
    "category.toys": "玩具",
    "category.books": "书籍",
    "category.beauty": "美容",
    "category.health": "健康",
    "category.automotive": "汽车",
    "category.tools": "工具",
    "category.garden": "园艺",
    "category.pets": "宠物",
    "category.baby": "婴儿",
    "category.office": "办公",
    "category.instruments": "乐器",
    "category.games": "游戏",
    "category.food": "食品",
    "category.drinks": "饮料",
    "category.cleaning": "清洁",
    "category.collectibles": "收藏品",
    "category.party": "派对",
    "category.industrial": "工业",
    "category.ppe": "个人防护装备",
    "category.services": "服务",
    "common.loading": "加载中...",
    "common.error": "错误",
    "common.success": "成功",
    "common.confirm": "确认",
    "common.cancel": "取消",
    "common.save": "保存",
    "common.edit": "编辑",
    "common.delete": "删除",
  },
  ar: {
    "header.search": "البحث عن المنتجات...",
    "header.cart": "عربة التسوق",
    "header.login": "تسجيل الدخول",
    "header.register": "التسجيل",
    "header.logout": "تسجيل الخروج",
    "header.myAccount": "حسابي",
    "header.panel": "لوحة التحكم",
    "home.title": "Achadinhos Xpress",
    "home.subtitle": "أفضل العروض في مكان واحد",
    "home.filters": "الفلاتر",
    "home.sortBy": "ترتيب حسب",
    "home.sortRecent": "الأحدث",
    "home.sortPriceLow": "السعر الأقل",
    "home.sortPriceHigh": "السعر الأعلى",
    "home.sortViews": "الأكثر مشاهدة",
    "home.stores": "المتاجر",
    "home.categories": "الفئات",
    "home.clearFilters": "مسح الفلاتر",
    "home.noProducts": "لم يتم العثور على منتجات",
    "home.viewOffer": "عرض العرض",
    "home.addToCart": "إضافة",
    "product.description": "الوصف",
    "product.characteristics": "الخصائص",
    "product.addToCart": "أضف إلى السلة",
    "product.buyNow": "اشتر الآن",
    "product.close": "إغلاق",
    "cart.title": "عربة التسوق",
    "cart.empty": "عربة التسوق فارغة",
    "cart.continueShopping": "متابعة التسوق",
    "cart.store": "المتجر",
    "cart.quantity": "الكمية",
    "cart.price": "السعر",
    "cart.total": "المجموع",
    "cart.remove": "إزالة",
    "cart.buy": "شراء",
    "cart.clearAll": "إفراغ السلة",
    "form.productCode": "رمز المنتج",
    "form.barcode": "الباركود",
    "form.globalCode": "الرمز العالمي",
    "form.stock": "الكمية في المخزون (اختياري)",
    "form.published": "مرئي على الموقع",
    "form.publishedHelp": "عند التفعيل، يظهر المنتج في الواجهة",
    "form.active": "متاح للبيع",
    "form.activeHelp": "عند التفعيل، يمكن إضافة المنتج إلى السلة",
    "category.fashion": "الموضة",
    "category.footwear": "الأحذية",
    "category.jewelry": "المجوهرات والإكسسوارات",
    "category.electronics": "الإلكترونيات",
    "category.appliances": "الأجهزة المنزلية",
    "category.furniture": "الأثاث",
    "category.sports": "الرياضة",
    "category.toys": "الألعاب",
    "category.books": "الكتب",
    "category.beauty": "الجمال",
    "category.health": "الصحة",
    "category.automotive": "السيارات",
    "category.tools": "الأدوات",
    "category.garden": "الحديقة",
    "category.pets": "الحيوانات الأليفة",
    "category.baby": "الأطفال",
    "category.office": "المكتب",
    "category.instruments": "الآلات الموسيقية",
    "category.games": "الألعاب",
    "category.food": "الطعام",
    "category.drinks": "المشروبات",
    "category.cleaning": "التنظيف",
    "category.collectibles": "المقتنيات",
    "category.party": "الحفلات",
    "category.industrial": "الصناعي",
    "category.ppe": "معدات الحماية الشخصية",
    "category.services": "الخدمات",
    "common.loading": "جاري التحميل...",
    "common.error": "خطأ",
    "common.success": "نجاح",
    "common.confirm": "تأكيد",
    "common.cancel": "إلغاء",
    "common.save": "حفظ",
    "common.edit": "تعديل",
    "common.delete": "حذف",
  },
  hi: {
    "header.search": "उत्पाद खोजें...",
    "header.cart": "कार्ट",
    "header.login": "लॉगिन",
    "header.register": "रजिस्टर",
    "header.logout": "लॉगआउट",
    "header.myAccount": "मेरा खाता",
    "header.panel": "पैनल",
    "home.title": "Achadinhos Xpress",
    "home.subtitle": "एक ही जगह पर सर्वोत्तम सौदे",
    "home.filters": "फ़िल्टर",
    "home.sortBy": "इसके अनुसार क्रमबद्ध करें",
    "home.sortRecent": "सबसे हाल का",
    "home.sortPriceLow": "सबसे कम कीमत",
    "home.sortPriceHigh": "सबसे अधिक कीमत",
    "home.sortViews": "सबसे अधिक देखे गए",
    "home.stores": "स्टोर",
    "home.categories": "श्रेणियाँ",
    "home.clearFilters": "फ़िल्टर साफ़ करें",
    "home.noProducts": "कोई उत्पाद नहीं मिला",
    "home.viewOffer": "ऑफ़र देखें",
    "home.addToCart": "जोड़ें",
    "product.description": "विवरण",
    "product.characteristics": "विशेषताएं",
    "product.addToCart": "कार्ट में जोड़ें",
    "product.buyNow": "अभी खरीदें",
    "product.close": "बंद करें",
    "cart.title": "शॉपिंग कार्ट",
    "cart.empty": "आपकी कार्ट खाली है",
    "cart.continueShopping": "खरीदारी जारी रखें",
    "cart.store": "स्टोर",
    "cart.quantity": "मात्रा",
    "cart.price": "कीमत",
    "cart.total": "कुल",
    "cart.remove": "हटाएं",
    "cart.buy": "खरीदें",
    "cart.clearAll": "कार्ट खाली करें",
    "form.productCode": "उत्पाद कोड",
    "form.barcode": "बारकोड",
    "form.globalCode": "वैश्विक कोड",
    "form.stock": "स्टॉक मात्रा (वैकल्पिक)",
    "form.published": "साइट पर दृश्यमान",
    "form.publishedHelp": "सक्षम होने पर, उत्पाद स्टोरफ्रंट में दिखाई देता है",
    "form.active": "बिक्री के लिए उपलब्ध",
    "form.activeHelp": "सक्षम होने पर, उत्पाद को कार्ट में जोड़ा जा सकता है",
    "category.fashion": "फैशन",
    "category.footwear": "जूते",
    "category.jewelry": "आभूषण और सहायक उपकरण",
    "category.electronics": "इलेक्ट्रॉनिक्स",
    "category.appliances": "उपकरण",
    "category.furniture": "फर्नीचर",
    "category.sports": "खेल",
    "category.toys": "खिलौने",
    "category.books": "किताबें",
    "category.beauty": "सौंदर्य",
    "category.health": "स्वास्थ्य",
    "category.automotive": "ऑटोमोटिव",
    "category.tools": "उपकरण",
    "category.garden": "बगीचा",
    "category.pets": "पालतू जानवर",
    "category.baby": "बच्चा",
    "category.office": "कार्यालय",
    "category.instruments": "संगीत वाद्ययंत्र",
    "category.games": "खेल",
    "category.food": "खाद्य पदार्थ",
    "category.drinks": "पेय",
    "category.cleaning": "सफाई",
    "category.collectibles": "संग्रहणीय",
    "category.party": "पार्टी",
    "category.industrial": "औद्योगिक",
    "category.ppe": "पीपीई",
    "category.services": "सेवाएं",
    "common.loading": "लोड हो रहा है...",
    "common.error": "त्रुटि",
    "common.success": "सफलता",
    "common.confirm": "पुष्टि करें",
    "common.cancel": "रद्द करें",
    "common.save": "सहेजें",
    "common.edit": "संपादित करें",
    "common.delete": "हटाएं",
  },
}

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>("pt")

  useEffect(() => {
    const saved = localStorage.getItem("language") as Language
    if (saved && ["pt", "en", "es", "fr", "de", "zh", "ar", "hi"].includes(saved)) {
      setLanguageState(saved)
    }
  }, [])

  const setLanguage = (lang: Language) => {
    setLanguageState(lang)
    localStorage.setItem("language", lang)
  }

  const t = (key: string): string => {
    return translations[language][key as keyof (typeof translations)["pt"]] || key
  }

  return <LanguageContext.Provider value={{ language, setLanguage, t }}>{children}</LanguageContext.Provider>
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (!context) {
    throw new Error("useLanguage must be used within LanguageProvider")
  }
  return context
}
